; Auto-generated. Do not edit!


(cl:in-package exploration_msgs-msg)


;//! \htmlinclude ExploreFeedback.msg.html

(cl:defclass <ExploreFeedback> (roslisp-msg-protocol:ros-message)
  ((next_frontier
    :reader next_frontier
    :initarg :next_frontier
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (base_position
    :reader base_position
    :initarg :base_position
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass ExploreFeedback (<ExploreFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExploreFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExploreFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name exploration_msgs-msg:<ExploreFeedback> is deprecated: use exploration_msgs-msg:ExploreFeedback instead.")))

(cl:ensure-generic-function 'next_frontier-val :lambda-list '(m))
(cl:defmethod next_frontier-val ((m <ExploreFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader exploration_msgs-msg:next_frontier-val is deprecated.  Use exploration_msgs-msg:next_frontier instead.")
  (next_frontier m))

(cl:ensure-generic-function 'base_position-val :lambda-list '(m))
(cl:defmethod base_position-val ((m <ExploreFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader exploration_msgs-msg:base_position-val is deprecated.  Use exploration_msgs-msg:base_position instead.")
  (base_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExploreFeedback>) ostream)
  "Serializes a message object of type '<ExploreFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'next_frontier) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'base_position) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExploreFeedback>) istream)
  "Deserializes a message object of type '<ExploreFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'next_frontier) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'base_position) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExploreFeedback>)))
  "Returns string type for a message object of type '<ExploreFeedback>"
  "exploration_msgs/ExploreFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExploreFeedback)))
  "Returns string type for a message object of type 'ExploreFeedback"
  "exploration_msgs/ExploreFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExploreFeedback>)))
  "Returns md5sum for a message object of type '<ExploreFeedback>"
  "00baaad5b6065fdad0f528586c3caaf2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExploreFeedback)))
  "Returns md5sum for a message object of type 'ExploreFeedback"
  "00baaad5b6065fdad0f528586c3caaf2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExploreFeedback>)))
  "Returns full string definition for message of type '<ExploreFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Current target frontier to explore~%geometry_msgs/PoseStamped next_frontier~%#Current position of robot~%geometry_msgs/PoseStamped base_position~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExploreFeedback)))
  "Returns full string definition for message of type 'ExploreFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Current target frontier to explore~%geometry_msgs/PoseStamped next_frontier~%#Current position of robot~%geometry_msgs/PoseStamped base_position~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExploreFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'next_frontier))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'base_position))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExploreFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExploreFeedback
    (cl:cons ':next_frontier (next_frontier msg))
    (cl:cons ':base_position (base_position msg))
))
